### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by wojcikstefan**
Most of the code contributed by @ghinch in https://github.com/closeio/closeio-api/pull/18

### CODE REVIEW

**Comment by anemitz** [comment]
What's the deal with this PR?

**Comment by szymonm** [comment]
Any updates on Python 3 compat?

**Comment by anemitz** [comment]
@wojcikstefan

**Comment by wojcikstefan** [comment]
Tested it w/ Py 3.5.0 and 2.7.11 - the `Client` as well as the scripts work fine.

**Comment by szymonm** [comment]
Thanks

**Comment by wojcikstefan** [comment]
@szymonm let me know if you discover any issues while using the API with Python 3.x. Pozdrowienia! :)

**Pull request merged**
