### PR TITLE
Merge Leads Script v2

### PR DESCRIPTION
**Pull request by anemitz**
- [x] Test phone number merging
- [x] Test company name merging

### CODE REVIEW

**Comment by anemitz** [comment]
This is currently on hold for an upstream change to the Close.io API.

**Comment by anemitz** [comment]
Programmatically merging leads is currently not recommended due to some issues we have discovered with the way our API works.

If you have relatively small leads (< 20 contacts, < 250 activities, etc) then this script should work fine. But if you have any large leads that will be merged *do not use this (or try and merge them in the UI)*. Merging of large leads can result in those leads being in an inconsistent state.

**Comment by steffensiewert** [comment]
Hi,

Ready for production?

Best

S

**Comment by anemitz** [comment]
The lead merging API still has considerable issues so if you get any errors during a merge stop and contact us with the relevant lead_ids.

**Pull request merged**
