### PR TITLE
Issue 59 - fix user reassign

### LINKED ISSUE #59: user_reassign script skips over objects
The user_reassign script doesn't update all the objects. It paginates through objects that match certain criteria (i.e. the old user), reassigns them to the new user, and then increases the `offset` to fetch the next batch. The problem is that when we reassign old objects, the results don't contain them anymore, and we end up skipping objects. We instead need to keep the `offset` at 0 and loop until no more objects are left (_except_ for in the dry run).

### PR DESCRIPTION
**Pull request by flevour**
Fixes #59 

All the changes are supported by TDD with functional tests hitting the live API. 

I'm not committing the tests but I can share them somewhere in case you want to have a look.

/cc @thomasst

### CODE REVIEW

**Comment by philfreo** [comment]
@flevour Let's go ahead and add the tests here now if they are in pretty good shape

**Comment by flevour** [comment]
@philfreo pushed tests

**Comment by flevour** [comment]
@philfreo @thomasst have you seen my last push?

**Comment by thomasst** [comment]
With this fix (sleeping 2 seconds in between fetches) we lose the ability to do a dry run, correct?

**Comment by flevour** [comment]
@thomasst I've moved the `sleep`-related logic inside the API wrapper so that the script will actually sleep only when running in confirmed mode. It will still log `sleeps` between fetched to clarify behaviour.

**Comment by flevour** [comment]
@thomasst in other words, your ability to do a dry run without incurring in sleep-related time penalties is now preserved (but it wasn't, so well spotted!).

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. @eengoron fyi if we want to unit tests our scripts, here's a nice example.

**Pull request closed without merging**
